services:

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080 #qbit webui
      - 6881:6881 # qbit torrent port
      - 6789:6789 # nzbget
      - 9696:9696 # prowlarr
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./media/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=  #################
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./media/qbittorrent:/config
      - /media/downloads:/downloads #optional
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: service:gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./media/prowlarr:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: service:gluetun
    
